FROM apache/airflow:2.9.0

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    pandas \
    psycopg2-binary \
    python-dotenv \
    requests \
    kafka-python
